// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jmfuncpvagluywlvxrdf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImptZnVuY3B2YWdsdXl3bHZ4cmRmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM4NTMyNDAsImV4cCI6MjA2OTQyOTI0MH0.MHEWuAF88hDcY-yN9NEgeZmSdpmV1LFlmRWS0mIRBHU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});